/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.C993;
import org.openapitools.client.model.C994;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ATI
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class ATI {
  public static final String SERIALIZED_NAME_C99301 = "C993_01";
  @SerializedName(SERIALIZED_NAME_C99301)
  private C993 C993_01;

  public static final String SERIALIZED_NAME_C99402 = "C994_02";
  @SerializedName(SERIALIZED_NAME_C99402)
  private List<C994> C994_02;

  public ATI() {
  }

  public ATI C993_01(C993 C993_01) {
    
    this.C993_01 = C993_01;
    return this;
  }

   /**
   * Get C993_01
   * @return C993_01
  **/
  @javax.annotation.Nullable

  public C993 getC99301() {
    return C993_01;
  }


  public void setC99301(C993 C993_01) {
    this.C993_01 = C993_01;
  }


  public ATI C994_02(List<C994> C994_02) {
    
    this.C994_02 = C994_02;
    return this;
  }

  public ATI addC99402Item(C994 C994_02Item) {
    if (this.C994_02 == null) {
      this.C994_02 = new ArrayList<>();
    }
    this.C994_02.add(C994_02Item);
    return this;
  }

   /**
   * Get C994_02
   * @return C994_02
  **/
  @javax.annotation.Nullable

  public List<C994> getC99402() {
    return C994_02;
  }


  public void setC99402(List<C994> C994_02) {
    this.C994_02 = C994_02;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ATI ATI = (ATI) o;
    return Objects.equals(this.C993_01, ATI.C993_01) &&
        Objects.equals(this.C994_02, ATI.C994_02);
  }

  @Override
  public int hashCode() {
    return Objects.hash(C993_01, C994_02);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ATI {\n");
    sb.append("    C993_01: ").append(toIndentedString(C993_01)).append("\n");
    sb.append("    C994_02: ").append(toIndentedString(C994_02)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("C993_01");
    openapiFields.add("C994_02");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ATI
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ATI.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ATI is not found in the empty JSON string", ATI.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ATI.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ATI` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `C993_01`
      if (jsonObj.get("C993_01") != null && !jsonObj.get("C993_01").isJsonNull()) {
        C993.validateJsonObject(jsonObj.getAsJsonObject("C993_01"));
      }
      if (jsonObj.get("C994_02") != null && !jsonObj.get("C994_02").isJsonNull()) {
        JsonArray jsonArrayC994_02 = jsonObj.getAsJsonArray("C994_02");
        if (jsonArrayC994_02 != null) {
          // ensure the json data is an array
          if (!jsonObj.get("C994_02").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `C994_02` to be an array in the JSON string but got `%s`", jsonObj.get("C994_02").toString()));
          }

          // validate the optional field `C994_02` (array)
          for (int i = 0; i < jsonArrayC994_02.size(); i++) {
            C994.validateJsonObject(jsonArrayC994_02.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ATI.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ATI' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ATI> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ATI.class));

       return (TypeAdapter<T>) new TypeAdapter<ATI>() {
           @Override
           public void write(JsonWriter out, ATI value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ATI read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ATI given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ATI
  * @throws IOException if the JSON string is invalid with respect to ATI
  */
  public static ATI fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ATI.class);
  }

 /**
  * Convert an instance of ATI to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

