/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.EDIFACTID6411;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * C317
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class C317 {
  public static final String SERIALIZED_NAME_MEASUREMENT_VALUE01 = "MeasurementValue_01";
  @SerializedName(SERIALIZED_NAME_MEASUREMENT_VALUE01)
  private String measurementValue01;

  public static final String SERIALIZED_NAME_MEASURE_UNIT_QUALIFIER02 = "MeasureUnitQualifier_02";
  @SerializedName(SERIALIZED_NAME_MEASURE_UNIT_QUALIFIER02)
  private EDIFACTID6411 measureUnitQualifier02;

  public static final String SERIALIZED_NAME_FIRST_TIME03 = "FirstTime_03";
  @SerializedName(SERIALIZED_NAME_FIRST_TIME03)
  private String firstTime03;

  public C317() {
  }

  public C317 measurementValue01(String measurementValue01) {
    
    this.measurementValue01 = measurementValue01;
    return this;
  }

   /**
   * Get measurementValue01
   * @return measurementValue01
  **/
  @javax.annotation.Nullable

  public String getMeasurementValue01() {
    return measurementValue01;
  }


  public void setMeasurementValue01(String measurementValue01) {
    this.measurementValue01 = measurementValue01;
  }


  public C317 measureUnitQualifier02(EDIFACTID6411 measureUnitQualifier02) {
    
    this.measureUnitQualifier02 = measureUnitQualifier02;
    return this;
  }

   /**
   * Get measureUnitQualifier02
   * @return measureUnitQualifier02
  **/
  @javax.annotation.Nullable

  public EDIFACTID6411 getMeasureUnitQualifier02() {
    return measureUnitQualifier02;
  }


  public void setMeasureUnitQualifier02(EDIFACTID6411 measureUnitQualifier02) {
    this.measureUnitQualifier02 = measureUnitQualifier02;
  }


  public C317 firstTime03(String firstTime03) {
    
    this.firstTime03 = firstTime03;
    return this;
  }

   /**
   * Get firstTime03
   * @return firstTime03
  **/
  @javax.annotation.Nullable

  public String getFirstTime03() {
    return firstTime03;
  }


  public void setFirstTime03(String firstTime03) {
    this.firstTime03 = firstTime03;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    C317 C317 = (C317) o;
    return Objects.equals(this.measurementValue01, C317.measurementValue01) &&
        Objects.equals(this.measureUnitQualifier02, C317.measureUnitQualifier02) &&
        Objects.equals(this.firstTime03, C317.firstTime03);
  }

  @Override
  public int hashCode() {
    return Objects.hash(measurementValue01, measureUnitQualifier02, firstTime03);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class C317 {\n");
    sb.append("    measurementValue01: ").append(toIndentedString(measurementValue01)).append("\n");
    sb.append("    measureUnitQualifier02: ").append(toIndentedString(measureUnitQualifier02)).append("\n");
    sb.append("    firstTime03: ").append(toIndentedString(firstTime03)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("MeasurementValue_01");
    openapiFields.add("MeasureUnitQualifier_02");
    openapiFields.add("FirstTime_03");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to C317
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!C317.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in C317 is not found in the empty JSON string", C317.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!C317.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `C317` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("MeasurementValue_01") != null && !jsonObj.get("MeasurementValue_01").isJsonNull()) && !jsonObj.get("MeasurementValue_01").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `MeasurementValue_01` to be a primitive type in the JSON string but got `%s`", jsonObj.get("MeasurementValue_01").toString()));
      }
      if ((jsonObj.get("FirstTime_03") != null && !jsonObj.get("FirstTime_03").isJsonNull()) && !jsonObj.get("FirstTime_03").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `FirstTime_03` to be a primitive type in the JSON string but got `%s`", jsonObj.get("FirstTime_03").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!C317.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'C317' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<C317> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(C317.class));

       return (TypeAdapter<T>) new TypeAdapter<C317>() {
           @Override
           public void write(JsonWriter out, C317 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public C317 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of C317 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of C317
  * @throws IOException if the JSON string is invalid with respect to C317
  */
  public static C317 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, C317.class);
  }

 /**
  * Convert an instance of C317 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

