/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.EDIFACTID7293;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * C337
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class C337 {
  public static final String SERIALIZED_NAME_SECTORSUBJECT_IDENTIFICATION_QUALIFIER01 = "SectorsubjectIdentificationQualifier_01";
  @SerializedName(SERIALIZED_NAME_SECTORSUBJECT_IDENTIFICATION_QUALIFIER01)
  private EDIFACTID7293 sectorsubjectIdentificationQualifier01;

  public static final String SERIALIZED_NAME_SECTORSUBJECT_IDENTIFICATION_QUALIFIER02 = "SectorsubjectIdentificationQualifier_02";
  @SerializedName(SERIALIZED_NAME_SECTORSUBJECT_IDENTIFICATION_QUALIFIER02)
  private EDIFACTID7293 sectorsubjectIdentificationQualifier02;

  public C337() {
  }

  public C337 sectorsubjectIdentificationQualifier01(EDIFACTID7293 sectorsubjectIdentificationQualifier01) {
    
    this.sectorsubjectIdentificationQualifier01 = sectorsubjectIdentificationQualifier01;
    return this;
  }

   /**
   * Get sectorsubjectIdentificationQualifier01
   * @return sectorsubjectIdentificationQualifier01
  **/
  @javax.annotation.Nonnull

  public EDIFACTID7293 getSectorsubjectIdentificationQualifier01() {
    return sectorsubjectIdentificationQualifier01;
  }


  public void setSectorsubjectIdentificationQualifier01(EDIFACTID7293 sectorsubjectIdentificationQualifier01) {
    this.sectorsubjectIdentificationQualifier01 = sectorsubjectIdentificationQualifier01;
  }


  public C337 sectorsubjectIdentificationQualifier02(EDIFACTID7293 sectorsubjectIdentificationQualifier02) {
    
    this.sectorsubjectIdentificationQualifier02 = sectorsubjectIdentificationQualifier02;
    return this;
  }

   /**
   * Get sectorsubjectIdentificationQualifier02
   * @return sectorsubjectIdentificationQualifier02
  **/
  @javax.annotation.Nullable

  public EDIFACTID7293 getSectorsubjectIdentificationQualifier02() {
    return sectorsubjectIdentificationQualifier02;
  }


  public void setSectorsubjectIdentificationQualifier02(EDIFACTID7293 sectorsubjectIdentificationQualifier02) {
    this.sectorsubjectIdentificationQualifier02 = sectorsubjectIdentificationQualifier02;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    C337 C337 = (C337) o;
    return Objects.equals(this.sectorsubjectIdentificationQualifier01, C337.sectorsubjectIdentificationQualifier01) &&
        Objects.equals(this.sectorsubjectIdentificationQualifier02, C337.sectorsubjectIdentificationQualifier02);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sectorsubjectIdentificationQualifier01, sectorsubjectIdentificationQualifier02);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class C337 {\n");
    sb.append("    sectorsubjectIdentificationQualifier01: ").append(toIndentedString(sectorsubjectIdentificationQualifier01)).append("\n");
    sb.append("    sectorsubjectIdentificationQualifier02: ").append(toIndentedString(sectorsubjectIdentificationQualifier02)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("SectorsubjectIdentificationQualifier_01");
    openapiFields.add("SectorsubjectIdentificationQualifier_02");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("SectorsubjectIdentificationQualifier_01");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to C337
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!C337.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in C337 is not found in the empty JSON string", C337.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!C337.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `C337` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : C337.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!C337.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'C337' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<C337> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(C337.class));

       return (TypeAdapter<T>) new TypeAdapter<C337>() {
           @Override
           public void write(JsonWriter out, C337 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public C337 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of C337 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of C337
  * @throws IOException if the JSON string is invalid with respect to C337
  */
  public static C337 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, C337.class);
  }

 /**
  * Convert an instance of C337 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

