/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.EDIFACTID3207;
import org.openapitools.client.model.EDIFACTID4405;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * C350
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class C350 {
  public static final String SERIALIZED_NAME_DOCUMENTMESSAGE_NUMBER01 = "DocumentmessageNumber_01";
  @SerializedName(SERIALIZED_NAME_DOCUMENTMESSAGE_NUMBER01)
  private String documentmessageNumber01;

  public static final String SERIALIZED_NAME_STATUS02 = "Status_02";
  @SerializedName(SERIALIZED_NAME_STATUS02)
  private EDIFACTID4405 status02;

  public static final String SERIALIZED_NAME_DATE_TIME_PERIOD03 = "DateTimePeriod_03";
  @SerializedName(SERIALIZED_NAME_DATE_TIME_PERIOD03)
  private String dateTimePeriod03;

  public static final String SERIALIZED_NAME_COUNTRY04 = "Country_04";
  @SerializedName(SERIALIZED_NAME_COUNTRY04)
  private EDIFACTID3207 country04;

  public C350() {
  }

  public C350 documentmessageNumber01(String documentmessageNumber01) {
    
    this.documentmessageNumber01 = documentmessageNumber01;
    return this;
  }

   /**
   * Get documentmessageNumber01
   * @return documentmessageNumber01
  **/
  @javax.annotation.Nullable

  public String getDocumentmessageNumber01() {
    return documentmessageNumber01;
  }


  public void setDocumentmessageNumber01(String documentmessageNumber01) {
    this.documentmessageNumber01 = documentmessageNumber01;
  }


  public C350 status02(EDIFACTID4405 status02) {
    
    this.status02 = status02;
    return this;
  }

   /**
   * Get status02
   * @return status02
  **/
  @javax.annotation.Nullable

  public EDIFACTID4405 getStatus02() {
    return status02;
  }


  public void setStatus02(EDIFACTID4405 status02) {
    this.status02 = status02;
  }


  public C350 dateTimePeriod03(String dateTimePeriod03) {
    
    this.dateTimePeriod03 = dateTimePeriod03;
    return this;
  }

   /**
   * Get dateTimePeriod03
   * @return dateTimePeriod03
  **/
  @javax.annotation.Nullable

  public String getDateTimePeriod03() {
    return dateTimePeriod03;
  }


  public void setDateTimePeriod03(String dateTimePeriod03) {
    this.dateTimePeriod03 = dateTimePeriod03;
  }


  public C350 country04(EDIFACTID3207 country04) {
    
    this.country04 = country04;
    return this;
  }

   /**
   * Get country04
   * @return country04
  **/
  @javax.annotation.Nullable

  public EDIFACTID3207 getCountry04() {
    return country04;
  }


  public void setCountry04(EDIFACTID3207 country04) {
    this.country04 = country04;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    C350 C350 = (C350) o;
    return Objects.equals(this.documentmessageNumber01, C350.documentmessageNumber01) &&
        Objects.equals(this.status02, C350.status02) &&
        Objects.equals(this.dateTimePeriod03, C350.dateTimePeriod03) &&
        Objects.equals(this.country04, C350.country04);
  }

  @Override
  public int hashCode() {
    return Objects.hash(documentmessageNumber01, status02, dateTimePeriod03, country04);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class C350 {\n");
    sb.append("    documentmessageNumber01: ").append(toIndentedString(documentmessageNumber01)).append("\n");
    sb.append("    status02: ").append(toIndentedString(status02)).append("\n");
    sb.append("    dateTimePeriod03: ").append(toIndentedString(dateTimePeriod03)).append("\n");
    sb.append("    country04: ").append(toIndentedString(country04)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("DocumentmessageNumber_01");
    openapiFields.add("Status_02");
    openapiFields.add("DateTimePeriod_03");
    openapiFields.add("Country_04");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to C350
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!C350.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in C350 is not found in the empty JSON string", C350.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!C350.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `C350` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("DocumentmessageNumber_01") != null && !jsonObj.get("DocumentmessageNumber_01").isJsonNull()) && !jsonObj.get("DocumentmessageNumber_01").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DocumentmessageNumber_01` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DocumentmessageNumber_01").toString()));
      }
      if ((jsonObj.get("DateTimePeriod_03") != null && !jsonObj.get("DateTimePeriod_03").isJsonNull()) && !jsonObj.get("DateTimePeriod_03").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DateTimePeriod_03` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DateTimePeriod_03").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!C350.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'C350' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<C350> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(C350.class));

       return (TypeAdapter<T>) new TypeAdapter<C350>() {
           @Override
           public void write(JsonWriter out, C350 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public C350 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of C350 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of C350
  * @throws IOException if the JSON string is invalid with respect to C350
  */
  public static C350 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, C350.class);
  }

 /**
  * Convert an instance of C350 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

