/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.EDIFACTID3207;
import org.openapitools.client.model.EDIFACTID3453;
import org.openapitools.client.model.EDIFACTID6345;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * C354
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class C354 {
  public static final String SERIALIZED_NAME_COUNTRY01 = "Country_01";
  @SerializedName(SERIALIZED_NAME_COUNTRY01)
  private EDIFACTID3207 country01;

  public static final String SERIALIZED_NAME_CURRENCY02 = "Currency_02";
  @SerializedName(SERIALIZED_NAME_CURRENCY02)
  private EDIFACTID6345 currency02;

  public static final String SERIALIZED_NAME_LANGUAGE03 = "Language_03";
  @SerializedName(SERIALIZED_NAME_LANGUAGE03)
  private EDIFACTID3453 language03;

  public C354() {
  }

  public C354 country01(EDIFACTID3207 country01) {
    
    this.country01 = country01;
    return this;
  }

   /**
   * Get country01
   * @return country01
  **/
  @javax.annotation.Nullable

  public EDIFACTID3207 getCountry01() {
    return country01;
  }


  public void setCountry01(EDIFACTID3207 country01) {
    this.country01 = country01;
  }


  public C354 currency02(EDIFACTID6345 currency02) {
    
    this.currency02 = currency02;
    return this;
  }

   /**
   * Get currency02
   * @return currency02
  **/
  @javax.annotation.Nullable

  public EDIFACTID6345 getCurrency02() {
    return currency02;
  }


  public void setCurrency02(EDIFACTID6345 currency02) {
    this.currency02 = currency02;
  }


  public C354 language03(EDIFACTID3453 language03) {
    
    this.language03 = language03;
    return this;
  }

   /**
   * Get language03
   * @return language03
  **/
  @javax.annotation.Nullable

  public EDIFACTID3453 getLanguage03() {
    return language03;
  }


  public void setLanguage03(EDIFACTID3453 language03) {
    this.language03 = language03;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    C354 C354 = (C354) o;
    return Objects.equals(this.country01, C354.country01) &&
        Objects.equals(this.currency02, C354.currency02) &&
        Objects.equals(this.language03, C354.language03);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country01, currency02, language03);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class C354 {\n");
    sb.append("    country01: ").append(toIndentedString(country01)).append("\n");
    sb.append("    currency02: ").append(toIndentedString(currency02)).append("\n");
    sb.append("    language03: ").append(toIndentedString(language03)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Country_01");
    openapiFields.add("Currency_02");
    openapiFields.add("Language_03");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to C354
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!C354.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in C354 is not found in the empty JSON string", C354.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!C354.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `C354` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!C354.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'C354' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<C354> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(C354.class));

       return (TypeAdapter<T>) new TypeAdapter<C354>() {
           @Override
           public void write(JsonWriter out, C354 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public C354 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of C354 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of C354
  * @throws IOException if the JSON string is invalid with respect to C354
  */
  public static C354 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, C354.class);
  }

 /**
  * Convert an instance of C354 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

