/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.EDIFACTID6353;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * C523
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class C523 {
  public static final String SERIALIZED_NAME_NUMBER_OF_UNITS01 = "NumberOfUnits_01";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_UNITS01)
  private String numberOfUnits01;

  public static final String SERIALIZED_NAME_NUMBER_OF_UNITS_QUALIFIER02 = "NumberOfUnitsQualifier_02";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_UNITS_QUALIFIER02)
  private EDIFACTID6353 numberOfUnitsQualifier02;

  public C523() {
  }

  public C523 numberOfUnits01(String numberOfUnits01) {
    
    this.numberOfUnits01 = numberOfUnits01;
    return this;
  }

   /**
   * Get numberOfUnits01
   * @return numberOfUnits01
  **/
  @javax.annotation.Nullable

  public String getNumberOfUnits01() {
    return numberOfUnits01;
  }


  public void setNumberOfUnits01(String numberOfUnits01) {
    this.numberOfUnits01 = numberOfUnits01;
  }


  public C523 numberOfUnitsQualifier02(EDIFACTID6353 numberOfUnitsQualifier02) {
    
    this.numberOfUnitsQualifier02 = numberOfUnitsQualifier02;
    return this;
  }

   /**
   * Get numberOfUnitsQualifier02
   * @return numberOfUnitsQualifier02
  **/
  @javax.annotation.Nullable

  public EDIFACTID6353 getNumberOfUnitsQualifier02() {
    return numberOfUnitsQualifier02;
  }


  public void setNumberOfUnitsQualifier02(EDIFACTID6353 numberOfUnitsQualifier02) {
    this.numberOfUnitsQualifier02 = numberOfUnitsQualifier02;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    C523 C523 = (C523) o;
    return Objects.equals(this.numberOfUnits01, C523.numberOfUnits01) &&
        Objects.equals(this.numberOfUnitsQualifier02, C523.numberOfUnitsQualifier02);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberOfUnits01, numberOfUnitsQualifier02);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class C523 {\n");
    sb.append("    numberOfUnits01: ").append(toIndentedString(numberOfUnits01)).append("\n");
    sb.append("    numberOfUnitsQualifier02: ").append(toIndentedString(numberOfUnitsQualifier02)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("NumberOfUnits_01");
    openapiFields.add("NumberOfUnitsQualifier_02");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to C523
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!C523.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in C523 is not found in the empty JSON string", C523.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!C523.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `C523` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("NumberOfUnits_01") != null && !jsonObj.get("NumberOfUnits_01").isJsonNull()) && !jsonObj.get("NumberOfUnits_01").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `NumberOfUnits_01` to be a primitive type in the JSON string but got `%s`", jsonObj.get("NumberOfUnits_01").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!C523.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'C523' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<C523> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(C523.class));

       return (TypeAdapter<T>) new TypeAdapter<C523>() {
           @Override
           public void write(JsonWriter out, C523 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public C523 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of C523 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of C523
  * @throws IOException if the JSON string is invalid with respect to C523
  */
  public static C523 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, C523.class);
  }

 /**
  * Convert an instance of C523 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

