/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets EDIFACT_ID_9988
 */
@JsonAdapter(EDIFACTID9988.Adapter.class)
public enum EDIFACTID9988 {
  
  _0("0"),
  
  _1("1"),
  
  _10("10"),
  
  _11("11"),
  
  _12("12"),
  
  _13("13"),
  
  _14("14"),
  
  _15("15"),
  
  _16("16"),
  
  _17("17"),
  
  _18("18"),
  
  _19("19"),
  
  _2("2"),
  
  _20("20"),
  
  _21("21"),
  
  _22("22"),
  
  _23("23"),
  
  _24("24"),
  
  _25("25"),
  
  _3("3"),
  
  _4("4"),
  
  _5("5"),
  
  _6("6"),
  
  _7("7"),
  
  _8("8"),
  
  _9("9"),
  
  AFT("AFT"),
  
  BEF("BEF"),
  
  DOM("DOM"),
  
  ECA("ECA"),
  
  EMP("EMP"),
  
  INT("INT"),
  
  LOC("LOC"),
  
  NOT("NOT"),
  
  SCH("SCH"),
  
  STP("STP"),
  
  TCT("TCT"),
  
  TIM("TIM"),
  
  TOT("TOT"),
  
  TRA("TRA"),
  
  TRS("TRS"),
  
  TWT("TWT"),
  
  VAL("VAL");

  private String value;

  EDIFACTID9988(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EDIFACTID9988 fromValue(String value) {
    for (EDIFACTID9988 b : EDIFACTID9988.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EDIFACTID9988> {
    @Override
    public void write(final JsonWriter jsonWriter, final EDIFACTID9988 enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EDIFACTID9988 read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EDIFACTID9988.fromValue(value);
    }
  }
}

