/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets EDIFACT_ID_9980
 */
@JsonAdapter(EDIFACTID9980.Adapter.class)
public enum EDIFACTID9980 {
  
  _1("1"),
  
  _10("10"),
  
  _101("101"),
  
  _102("102"),
  
  _11("11"),
  
  _12("12"),
  
  _13("13"),
  
  _14("14"),
  
  _15("15"),
  
  _16("16"),
  
  _17("17"),
  
  _18("18"),
  
  _19("19"),
  
  _2("2"),
  
  _20("20"),
  
  _21("21"),
  
  _22("22"),
  
  _23("23"),
  
  _24("24"),
  
  _25("25"),
  
  _26("26"),
  
  _27("27"),
  
  _28("28"),
  
  _29("29"),
  
  _3("3"),
  
  _30("30"),
  
  _31("31"),
  
  _32("32"),
  
  _33("33"),
  
  _34("34"),
  
  _35("35"),
  
  _36("36"),
  
  _37("37"),
  
  _38("38"),
  
  _39("39"),
  
  _4("4"),
  
  _40("40"),
  
  _41("41"),
  
  _42("42"),
  
  _43("43"),
  
  _45("45"),
  
  _46("46"),
  
  _47("47"),
  
  _5("5"),
  
  _50("50"),
  
  _51("51"),
  
  _52("52"),
  
  _53("53"),
  
  _54("54"),
  
  _55("55"),
  
  _56("56"),
  
  _57("57"),
  
  _58("58"),
  
  _59("59"),
  
  _6("6"),
  
  _60("60"),
  
  _61("61"),
  
  _62("62"),
  
  _63("63"),
  
  _64("64"),
  
  _65("65"),
  
  _66("66"),
  
  _67("67"),
  
  _68("68"),
  
  _69("69"),
  
  _7("7"),
  
  _700("700"),
  
  _701("701"),
  
  _702("702"),
  
  _703("703"),
  
  _704("704"),
  
  _705("705"),
  
  _706("706"),
  
  _707("707"),
  
  _708("708"),
  
  _709("709"),
  
  _710("710"),
  
  _711("711"),
  
  _712("712"),
  
  _713("713"),
  
  _714("714"),
  
  _715("715"),
  
  _716("716"),
  
  _717("717"),
  
  _718("718"),
  
  _719("719"),
  
  _720("720"),
  
  _721("721"),
  
  _722("722"),
  
  _723("723"),
  
  _724("724"),
  
  _725("725"),
  
  _726("726"),
  
  _727("727"),
  
  _728("728"),
  
  _729("729"),
  
  _730("730"),
  
  _731("731"),
  
  _732("732"),
  
  _733("733"),
  
  _734("734"),
  
  _735("735"),
  
  _7EX("7EX"),
  
  _7FC("7FC"),
  
  _7NU("7NU"),
  
  _7NV("7NV"),
  
  _7RV("7RV"),
  
  _8("8"),
  
  _9("9"),
  
  AHS("AHS"),
  
  BD("BD"),
  
  BI("BI"),
  
  DHS("DHS"),
  
  FAA("FAA"),
  
  ISR("ISR"),
  
  OD("OD"),
  
  OI("OI"),
  
  TXT("TXT");

  private String value;

  EDIFACTID9980(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EDIFACTID9980 fromValue(String value) {
    for (EDIFACTID9980 b : EDIFACTID9980.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EDIFACTID9980> {
    @Override
    public void write(final JsonWriter jsonWriter, final EDIFACTID9980 enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EDIFACTID9980 read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EDIFACTID9980.fromValue(value);
    }
  }
}

