/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets EDIFACT_ID_9989
 */
@JsonAdapter(EDIFACTID9989.Adapter.class)
public enum EDIFACTID9989 {
  
  _700("700"),
  
  _701("701"),
  
  _702("702"),
  
  _703("703"),
  
  _704("704"),
  
  _705("705"),
  
  _706("706"),
  
  _707("707"),
  
  _708("708"),
  
  _709("709"),
  
  _710("710"),
  
  _711("711"),
  
  _712("712"),
  
  _713("713"),
  
  _714("714"),
  
  ADT("ADT"),
  
  ARE("ARE"),
  
  BAG("BAG"),
  
  CHD("CHD"),
  
  CRO("CRO"),
  
  CRW("CRW"),
  
  CUS("CUS"),
  
  DEL("DEL"),
  
  DHD("DHD"),
  
  FEM("FEM"),
  
  FRT("FRT"),
  
  INF("INF"),
  
  MAI("MAI"),
  
  MAL("MAL"),
  
  NOI("NOI"),
  
  NOT("NOT"),
  
  NRV("NRV"),
  
  PAX("PAX"),
  
  REV("REV"),
  
  TME("TME"),
  
  TOF("TOF");

  private String value;

  EDIFACTID9989(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EDIFACTID9989 fromValue(String value) {
    for (EDIFACTID9989 b : EDIFACTID9989.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EDIFACTID9989> {
    @Override
    public void write(final JsonWriter jsonWriter, final EDIFACTID9989 enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EDIFACTID9989 read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EDIFACTID9989.fromValue(value);
    }
  }
}

