/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets EDIFACT_ID_0113
 */
@JsonAdapter(EDIFACTID0113.Adapter.class)
public enum EDIFACTID0113 {
  
  AA("AA"),
  
  AB("AB"),
  
  AC("AC"),
  
  AD("AD"),
  
  AE("AE"),
  
  AF("AF"),
  
  AG("AG"),
  
  AH("AH"),
  
  AI("AI"),
  
  AJ("AJ"),
  
  AK("AK"),
  
  AL("AL"),
  
  AM("AM"),
  
  AN("AN"),
  
  AO("AO"),
  
  AP("AP"),
  
  AQ("AQ"),
  
  AR("AR"),
  
  AS("AS"),
  
  SECACK("SECACK"),
  
  SECAUT("SECAUT");

  private String value;

  EDIFACTID0113(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static EDIFACTID0113 fromValue(String value) {
    for (EDIFACTID0113 b : EDIFACTID0113.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<EDIFACTID0113> {
    @Override
    public void write(final JsonWriter jsonWriter, final EDIFACTID0113 enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public EDIFACTID0113 read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return EDIFACTID0113.fromValue(value);
    }
  }
}

