/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.EQI;
import org.openapitools.client.model.TII;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * LoopTIITKTREQ
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class LoopTIITKTREQ {
  public static final String SERIALIZED_NAME_T_I_I = "TII";
  @SerializedName(SERIALIZED_NAME_T_I_I)
  private TII tii;

  public static final String SERIALIZED_NAME_E_Q_I = "EQI";
  @SerializedName(SERIALIZED_NAME_E_Q_I)
  private EQI eqi;

  public LoopTIITKTREQ() {
  }

  public LoopTIITKTREQ tii(TII tii) {
    
    this.tii = tii;
    return this;
  }

   /**
   * Get tii
   * @return tii
  **/
  @javax.annotation.Nonnull

  public TII getTII() {
    return tii;
  }


  public void setTII(TII tii) {
    this.tii = tii;
  }


  public LoopTIITKTREQ eqi(EQI eqi) {
    
    this.eqi = eqi;
    return this;
  }

   /**
   * Get eqi
   * @return eqi
  **/
  @javax.annotation.Nullable

  public EQI getEQI() {
    return eqi;
  }


  public void setEQI(EQI eqi) {
    this.eqi = eqi;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoopTIITKTREQ loopTIITKTREQ = (LoopTIITKTREQ) o;
    return Objects.equals(this.tii, loopTIITKTREQ.tii) &&
        Objects.equals(this.eqi, loopTIITKTREQ.eqi);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tii, eqi);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoopTIITKTREQ {\n");
    sb.append("    tii: ").append(toIndentedString(tii)).append("\n");
    sb.append("    eqi: ").append(toIndentedString(eqi)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("TII");
    openapiFields.add("EQI");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("TII");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to LoopTIITKTREQ
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!LoopTIITKTREQ.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in LoopTIITKTREQ is not found in the empty JSON string", LoopTIITKTREQ.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!LoopTIITKTREQ.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `LoopTIITKTREQ` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : LoopTIITKTREQ.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `TII`
      TII.validateJsonObject(jsonObj.getAsJsonObject("TII"));
      // validate the optional field `EQI`
      if (jsonObj.get("EQI") != null && !jsonObj.get("EQI").isJsonNull()) {
        EQI.validateJsonObject(jsonObj.getAsJsonObject("EQI"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!LoopTIITKTREQ.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'LoopTIITKTREQ' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<LoopTIITKTREQ> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(LoopTIITKTREQ.class));

       return (TypeAdapter<T>) new TypeAdapter<LoopTIITKTREQ>() {
           @Override
           public void write(JsonWriter out, LoopTIITKTREQ value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public LoopTIITKTREQ read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of LoopTIITKTREQ given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of LoopTIITKTREQ
  * @throws IOException if the JSON string is invalid with respect to LoopTIITKTREQ
  */
  public static LoopTIITKTREQ fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, LoopTIITKTREQ.class);
  }

 /**
  * Convert an instance of LoopTIITKTREQ to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

