/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import org.openapitools.client.model.C302;
import org.openapitools.client.model.EDIFACTID4343;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * MSG
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class MSG {
  public static final String SERIALIZED_NAME_C30201 = "C302_01";
  @SerializedName(SERIALIZED_NAME_C30201)
  private C302 C302_01;

  public static final String SERIALIZED_NAME_RESPONSE_TYPE02 = "ResponseType_02";
  @SerializedName(SERIALIZED_NAME_RESPONSE_TYPE02)
  private EDIFACTID4343 responseType02;

  public MSG() {
  }

  public MSG C302_01(C302 C302_01) {
    
    this.C302_01 = C302_01;
    return this;
  }

   /**
   * Get C302_01
   * @return C302_01
  **/
  @javax.annotation.Nullable

  public C302 getC30201() {
    return C302_01;
  }


  public void setC30201(C302 C302_01) {
    this.C302_01 = C302_01;
  }


  public MSG responseType02(EDIFACTID4343 responseType02) {
    
    this.responseType02 = responseType02;
    return this;
  }

   /**
   * Get responseType02
   * @return responseType02
  **/
  @javax.annotation.Nullable

  public EDIFACTID4343 getResponseType02() {
    return responseType02;
  }


  public void setResponseType02(EDIFACTID4343 responseType02) {
    this.responseType02 = responseType02;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MSG MSG = (MSG) o;
    return Objects.equals(this.C302_01, MSG.C302_01) &&
        Objects.equals(this.responseType02, MSG.responseType02);
  }

  @Override
  public int hashCode() {
    return Objects.hash(C302_01, responseType02);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MSG {\n");
    sb.append("    C302_01: ").append(toIndentedString(C302_01)).append("\n");
    sb.append("    responseType02: ").append(toIndentedString(responseType02)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("C302_01");
    openapiFields.add("ResponseType_02");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to MSG
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!MSG.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in MSG is not found in the empty JSON string", MSG.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!MSG.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `MSG` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      // validate the optional field `C302_01`
      if (jsonObj.get("C302_01") != null && !jsonObj.get("C302_01").isJsonNull()) {
        C302.validateJsonObject(jsonObj.getAsJsonObject("C302_01"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!MSG.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'MSG' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<MSG> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(MSG.class));

       return (TypeAdapter<T>) new TypeAdapter<MSG>() {
           @Override
           public void write(JsonWriter out, MSG value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public MSG read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of MSG given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of MSG
  * @throws IOException if the JSON string is invalid with respect to MSG
  */
  public static MSG fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, MSG.class);
  }

 /**
  * Convert an instance of MSG to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

