/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.C642;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * TAI
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class TAI {
  public static final String SERIALIZED_NAME_COMPANY_IDENTIFICATION_NUMBER01 = "CompanyIdentificationNumber_01";
  @SerializedName(SERIALIZED_NAME_COMPANY_IDENTIFICATION_NUMBER01)
  private String companyIdentificationNumber01;

  public static final String SERIALIZED_NAME_C64202 = "C642_02";
  @SerializedName(SERIALIZED_NAME_C64202)
  private List<C642> C642_02;

  public TAI() {
  }

  public TAI companyIdentificationNumber01(String companyIdentificationNumber01) {
    
    this.companyIdentificationNumber01 = companyIdentificationNumber01;
    return this;
  }

   /**
   * Get companyIdentificationNumber01
   * @return companyIdentificationNumber01
  **/
  @javax.annotation.Nullable

  public String getCompanyIdentificationNumber01() {
    return companyIdentificationNumber01;
  }


  public void setCompanyIdentificationNumber01(String companyIdentificationNumber01) {
    this.companyIdentificationNumber01 = companyIdentificationNumber01;
  }


  public TAI C642_02(List<C642> C642_02) {
    
    this.C642_02 = C642_02;
    return this;
  }

  public TAI addC64202Item(C642 C642_02Item) {
    if (this.C642_02 == null) {
      this.C642_02 = new ArrayList<>();
    }
    this.C642_02.add(C642_02Item);
    return this;
  }

   /**
   * Get C642_02
   * @return C642_02
  **/
  @javax.annotation.Nullable

  public List<C642> getC64202() {
    return C642_02;
  }


  public void setC64202(List<C642> C642_02) {
    this.C642_02 = C642_02;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TAI TAI = (TAI) o;
    return Objects.equals(this.companyIdentificationNumber01, TAI.companyIdentificationNumber01) &&
        Objects.equals(this.C642_02, TAI.C642_02);
  }

  @Override
  public int hashCode() {
    return Objects.hash(companyIdentificationNumber01, C642_02);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TAI {\n");
    sb.append("    companyIdentificationNumber01: ").append(toIndentedString(companyIdentificationNumber01)).append("\n");
    sb.append("    C642_02: ").append(toIndentedString(C642_02)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CompanyIdentificationNumber_01");
    openapiFields.add("C642_02");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TAI
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TAI.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TAI is not found in the empty JSON string", TAI.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!TAI.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `TAI` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if ((jsonObj.get("CompanyIdentificationNumber_01") != null && !jsonObj.get("CompanyIdentificationNumber_01").isJsonNull()) && !jsonObj.get("CompanyIdentificationNumber_01").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `CompanyIdentificationNumber_01` to be a primitive type in the JSON string but got `%s`", jsonObj.get("CompanyIdentificationNumber_01").toString()));
      }
      if (jsonObj.get("C642_02") != null && !jsonObj.get("C642_02").isJsonNull()) {
        JsonArray jsonArrayC642_02 = jsonObj.getAsJsonArray("C642_02");
        if (jsonArrayC642_02 != null) {
          // ensure the json data is an array
          if (!jsonObj.get("C642_02").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `C642_02` to be an array in the JSON string but got `%s`", jsonObj.get("C642_02").toString()));
          }

          // validate the optional field `C642_02` (array)
          for (int i = 0; i < jsonArrayC642_02.size(); i++) {
            C642.validateJsonObject(jsonArrayC642_02.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TAI.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TAI' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TAI> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TAI.class));

       return (TypeAdapter<T>) new TypeAdapter<TAI>() {
           @Override
           public void write(JsonWriter out, TAI value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public TAI read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TAI given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TAI
  * @throws IOException if the JSON string is invalid with respect to TAI
  */
  public static TAI fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TAI.class);
  }

 /**
  * Convert an instance of TAI to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

