/*
 * EdiNation API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * UNT
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-09T20:30:51.657048-10:00[Pacific/Honolulu]")
public class UNT {
  public static final String SERIALIZED_NAME_NUMBEROF_SEGMENTSINA_MESSAGE01 = "NumberofSegmentsinaMessage_01";
  @SerializedName(SERIALIZED_NAME_NUMBEROF_SEGMENTSINA_MESSAGE01)
  private String numberofSegmentsinaMessage01;

  public static final String SERIALIZED_NAME_MESSAGE_REFERENCE_NUMBER02 = "MessageReferenceNumber_02";
  @SerializedName(SERIALIZED_NAME_MESSAGE_REFERENCE_NUMBER02)
  private String messageReferenceNumber02;

  public UNT() {
  }

  public UNT numberofSegmentsinaMessage01(String numberofSegmentsinaMessage01) {
    
    this.numberofSegmentsinaMessage01 = numberofSegmentsinaMessage01;
    return this;
  }

   /**
   * Get numberofSegmentsinaMessage01
   * @return numberofSegmentsinaMessage01
  **/
  @javax.annotation.Nonnull

  public String getNumberofSegmentsinaMessage01() {
    return numberofSegmentsinaMessage01;
  }


  public void setNumberofSegmentsinaMessage01(String numberofSegmentsinaMessage01) {
    this.numberofSegmentsinaMessage01 = numberofSegmentsinaMessage01;
  }


  public UNT messageReferenceNumber02(String messageReferenceNumber02) {
    
    this.messageReferenceNumber02 = messageReferenceNumber02;
    return this;
  }

   /**
   * Get messageReferenceNumber02
   * @return messageReferenceNumber02
  **/
  @javax.annotation.Nonnull

  public String getMessageReferenceNumber02() {
    return messageReferenceNumber02;
  }


  public void setMessageReferenceNumber02(String messageReferenceNumber02) {
    this.messageReferenceNumber02 = messageReferenceNumber02;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UNT UNT = (UNT) o;
    return Objects.equals(this.numberofSegmentsinaMessage01, UNT.numberofSegmentsinaMessage01) &&
        Objects.equals(this.messageReferenceNumber02, UNT.messageReferenceNumber02);
  }

  @Override
  public int hashCode() {
    return Objects.hash(numberofSegmentsinaMessage01, messageReferenceNumber02);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UNT {\n");
    sb.append("    numberofSegmentsinaMessage01: ").append(toIndentedString(numberofSegmentsinaMessage01)).append("\n");
    sb.append("    messageReferenceNumber02: ").append(toIndentedString(messageReferenceNumber02)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("NumberofSegmentsinaMessage_01");
    openapiFields.add("MessageReferenceNumber_02");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("NumberofSegmentsinaMessage_01");
    openapiRequiredFields.add("MessageReferenceNumber_02");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to UNT
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!UNT.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in UNT is not found in the empty JSON string", UNT.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!UNT.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `UNT` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UNT.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("NumberofSegmentsinaMessage_01").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `NumberofSegmentsinaMessage_01` to be a primitive type in the JSON string but got `%s`", jsonObj.get("NumberofSegmentsinaMessage_01").toString()));
      }
      if (!jsonObj.get("MessageReferenceNumber_02").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `MessageReferenceNumber_02` to be a primitive type in the JSON string but got `%s`", jsonObj.get("MessageReferenceNumber_02").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UNT.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UNT' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UNT> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UNT.class));

       return (TypeAdapter<T>) new TypeAdapter<UNT>() {
           @Override
           public void write(JsonWriter out, UNT value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UNT read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of UNT given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of UNT
  * @throws IOException if the JSON string is invalid with respect to UNT
  */
  public static UNT fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UNT.class);
  }

 /**
  * Convert an instance of UNT to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

